config/routes.rb
Rails.application.routes.draw do

  def scoped_controller name, &block
    scope name, controller: name, as: name, &block
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "public#index"

  get 'uzivatel' => 'session#show', as: :session
  get 'faktura/:slug' => 'public#invoice', as: nil
  get 'faktury' => 'invoices#index', as: nil

  scope :session, controller: :session, as: :session do
    get :show
    post :create
    post :destroy
  end

  resources :users
  resources :invoices

end

app/models/invoice.rb
class Invoice < ApplicationRecord

    belongs_to :user, optional: true
    has_many :reminders, dependent: :destroy

    validates :buyer_email, presence: true
    validates :buyer_name, presence: true
    validates :due_date, presence: true
    validates :price_amount, presence: true

    before_create :set_public_slug

    def send_next_reminder!
        if reminders.count.zero?
            InvoiceReminderMailer.new_invoice(self, save: true).deliver_later
        else

        end
    end

private

    def set_public_slug
        self.public_slug = SecureRandom.uuid
    end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    before_action :require_user_session
    before_action :require_admin, only: %i[ new create edit update destroy ]
    before_action :set_invoice, only: %i[ show edit update destroy ]

  def index
    @invoices = Invoice.all
    unless current_user.is_admin?
      @invoices = @invoices.where user: current_user
    end
    @invoices.order due_date: :desc

    if param = params[:search].presence
      search_term = "%#{param}%"
      @invoices = @invoices.where 'buyer_name LIKE ? OR buyer_email LIKE ?', search_term, search_term
    end
  end

  def show
  end

  def new
    @invoice = Invoice.new
  end

  def edit
  end

  def create
    @invoice = Invoice.new invoice_params
    @invoice.user = User.find_by email: @invoice.buyer_email

    if @invoice.save
      @invoice.send_next_reminder!
      redirect_to invoice_url(@invoice), notice: "Invoice was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @invoice.update invoice_params
      redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @invoice.destroy!

    respond_to do |format|
      redirect_to invoices_url, notice: "Invoice was successfully destroyed."
    end
  end

private

  def set_invoice
    @invoice = Invoice.find params[:id]
  end

  def invoice_params
    values = params.require(:invoice).permit(
      :buyer_email, :buyer_name, :buyer_address, :buyer_phonem, :due_date, :price_amount, :note
    )
    values[:due_date] = TextFormattingHelper.cast_cz_date values[:due_date]
    values[:price_amount] = TextFormattingHelper.cast_czk_amount values[:price_amount]
    values
  end

end

app/views/invoices/_form.html.erb
<%= form_with model: invoice do |form| %>
  <div class="row">
    <%= render 'form_errors', model: invoice %>
  </div>

  <div class="row mt-2">
    <div class="col-md-6 col-lg-4">
      <div class="mb-3">
        <%= form.label :buyer_email, class: 'form-label' %>
        <%= form.text_field :buyer_email, class: 'form-control' %>
      </div>

      <div  class="mb-3">
        <%= form.label :buyer_name, class: 'form-label' %>
        <%= form.text_field :buyer_name, class: 'form-control' %>
      </div>

      <div  class="mb-3">
        <%= form.label :buyer_address, class: 'form-label' %>
        <%= form.text_field :buyer_address, class: 'form-control' %>
      </div>

      <div  class="mb-3">
        <%= form.label :buyer_phone, class: 'form-label' %>
        <%= form.text_field :buyer_phone, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6 col-lg-4">
      <div  class="mb-3">
        <%= form.label :due_date, class: 'form-label' %>
        <%= form.text_field :due_date, class: 'form-control', value: format_cz_date(invoice.due_date)  %>
      </div>

      <div  class="mb-3">
        <%= form.label :price_amount, class: 'form-label' %>
        <%= form.text_field :price_amount, class: 'form-control', value: format_czk_amount(invoice.price_amount, show_unit: false)  %>
      </div>

      <div class="mb-3">
        <%= form.label :note, class: 'form-label' %>
        <%= form.text_area :note, class: 'form-control', rows: 6  %>
      </div>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<%= render 'form_page_header', text: 'Úprava faktury', back_path: invoice_path(@invoice) %>

<%= render "form", invoice: @invoice %>

app/views/invoices/index.html.erb
<h1 class="mt-4">Faktury</h1>

<% invoices, pages = paginate_records @invoices %>

<nav class="d-flex gap-2 justify-content-between align-items-center">
  <%= render 'pagination', pages: %>
  <%= render 'search_form', path: invoices_path %>
  <% if current_user.is_admin? %>
    <div class="d-flex gap-2">
      <%= link_to new_invoice_path, class: 'text-decoration-none' do %>
        <i class="bi bi-receipt"></i>
        Vložit fakturu
      <% end %>
    </div>
  <% end %>
</nav>

<div id="invoices" class="mt-3 text-center row">
  <% invoices.each do |invoice| %>
    <div class="col-sm-6 col-md-4 col-lg-3 mb-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
            <strong><%= Invoice.human_attribute_name(:buyer_name) %>:</strong>
            <%= invoice.buyer_name %>
          </h5>
          <h6>
            <%= format_cz_date invoice.due_date %>
            <br>
            <%= format_czk_amount invoice.price_amount %>
          </h6>
          <p class="card-text mt-2">
            <strong><%= Invoice.human_attribute_name(:buyer_email) %>:</strong>
            <%= invoice.buyer_email %>
          </p>
          <% if invoice.buyer_address.present? %>
            <p class="card-text">
                <strong><%= Invoice.human_attribute_name(:buyer_address) %>:</strong>
                <%= invoice.buyer_address %>
            </p>
          <% end %>
          <%= link_to "Detail", invoice, class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/invoices/new.html.erb
<%= render 'form_page_header', text: 'Nová faktura', back_path: invoices_path %>

<div class="mt-3">
  <%= render "form", invoice: @invoice %>
</div>

app/views/invoices/show.html.erb
<h1 class="mt-4">Detail faktury</h1>

<div class="row">

  <div class="col-md-6 col-lg-4">

    <div class="mb-3">
      <strong><%= Invoice.human_attribute_name(:buyer_email) %></strong><br>
      <%= @invoice.buyer_email %>
    </div>
    <div class="mb-3">
      <strong><%= Invoice.human_attribute_name(:buyer_name) %></strong><br>
      <%= @invoice.buyer_name %>
    </div>
    <div class="mb-3">
      <strong><%= Invoice.human_attribute_name(:buyer_address) %></strong><br>
      <%= @invoice.buyer_address %>
    </div>
    <div class="mb-3">
      <strong><%= Invoice.human_attribute_name(:buyer_phone) %></strong><br>
      <%= @invoice.buyer_phone %>
    </div>

  </div>

  <div class="col-md-6 col-lg-4">
    <div class="mb-3">
      <strong><%= Invoice.human_attribute_name(:due_date) %></strong><br>
      <%= format_cz_date @invoice.due_date %>
    </div>
    <div class="mb-3">
      <strong><%= Invoice.human_attribute_name(:price_amount) %></strong><br>
      <%= format_czk_amount @invoice.price_amount %>
    </div>
    <div class="mb-3">
      <strong><%= Invoice.human_attribute_name(:note) %></strong><br>
      <small>
        <%= @invoice.note %>
      </small>
    </div>
  </div>

</div>