config/routes.rb
Rails.application.routes.draw do

  def scoped_controller name, &block
    scope name, controller: name, as: name, &block
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "public#index"

  get 'uzivatel' => 'session#show', as: :session
  get 'faktura/:slug' => 'public#invoice', as: nil
  get 'faktury' => 'invoices#index', as: nil

  scope :session, controller: :session, as: :session do
    get :show
    post :create
    post :destroy
  end

  resources :users
  resources :invoices

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def show
  end

  def create
    @session_email = params[:session_email].presence.strip
    user = User.find_by email: @session_email

    unless user
      @session_fail = :unknown_email
      render turbo_stream: turbo_stream.replace('session_login', partial: 'login')
      return
    end

    unless user.authenticate params[:session_password]
      @session_fail = :bad_password
      render turbo_stream: turbo_stream.replace('session_login', partial: 'login')
      return
    end

    session[:user_id] = user.id
    render turbo_stream: turbo_stream.replace('session_login', partial: 'actions/redirect', locals: { url: session_path })
  end

  def destroy
    reset_session
    redirect_to root_path, alert: 'Proběhlo odhlášení.'
  end

end

app/views/session/_detail.html.haml
%h2 Přihlásený uživatel
%p= current_user.email

= form_with url: session_destroy_path, local: true do |form|
  .mb-3
    %button.btn.btn-link.px-0{ type: 'submit' } Odhlásit se

app/views/session/_login.html.haml
= form_with url: session_create_path, data: { turbo_frame: "session_login" } do |form|
  %h1.text-center.mt-4 Přihlášení uživatele
  .mb-3
    %label.form-label{ for: 'session_email' } Email
    %input.form-control{ type: 'text', id: 'session_email', name: 'session_email', value: @session_email }
    - if @session_fail == :unknown_email
      .alert.alert-info.mt-1.p-2 Pod tímto emailem nemáme zaznamenou žádnou nezaplacenou fakturu.
  .mb-3
    %label.form-label{ for: 'session_passowrd' } Heslo
    %input.form-control{ type: 'password', id: 'session_password', name: 'session_password' }
    - if @session_fail == :bad_password
      .alert.alert-danger.mt-1.p-2 Nesprávné heslo
  .mb-3
    %button.btn.btn-primary{ type: 'submit' } Přihlášení

app/views/session/show.html.haml
.mt-4.row.justify-content-center
  .col-sm-10.col-md-8.col-lg-6.col-xl-4
    - if current_user
      = render 'detail'
    - else
      = turbo_frame_tag 'session_login' do
        = render 'login'